### PR TITLE
Add API script to output JSON list of routers with MAC address

### PR DESCRIPTION
**Pull request by adridolf**
I would like this API script as I have a self-made C# administration program for my routers based on the monitoring.

At the moment, I'm parsing the routers overview html page which is not very nice or efficient...

This would make it much easier (and include the mac addresses)

### CODE REVIEW

**Comment by asdil12** [comment]
Looks nice - I just would rather use something like `/routers.json` as the path.
Please update the PR and I'll accept it.

**Comment by asdil12** [comment]
`/routers` is ok as well.

**Comment by adridolf** [comment]
Rebased, changed to /api/routers, and added fastd/l2tp uplink interface count.

**Comment by asdil12** [comment]
Please rebase again.

**Comment by adridolf** [comment]
Rebased again.

**Comment by adridolf** [comment]
Kannst du das bei Gelegenheit mit install.sh aktiv machen?

**Pull request merged**
